### ISSUE TITLE
Brew longer supports --with

### ISSUE THREAD

**Issue by adamhsparks** [sethrfore/homebrew-r-srf#10]
So `--with-cairo --with-libtiff --with-openblas`, etc. no longer will work.

**Comment by sethrfore** [comment]
I just installed with the options you've listed with no problems. So, did you read the instructions? If you've followed the instructions and still have an error, I'd be more inclined to help if you provide a more informative error log...

**Comment by adamhsparks** [comment]
OK, sorry for bothering you. I just reinstalled Homebrew freshly on one of my computers and it didn't work as it had several times in the past and in my own instructions which use your repository as a reference. 

I'd be more inclined to help you if you were a bit more kind. 

I'll figure it out anyway.

**Comment by sethrfore** [comment]
I did not intend to be overly brusque and I am interested in solving a problem if one exists. I verified that the formula installs correctly on my end prior to addressing your issue and in the absence of any sort of error description on your end I do not know what needs fixing. If you have issues after following the installation instructions file a new issue and I'll see if I can help.
