### ISSUE TITLE
No X11 capabilities

### ISSUE THREAD

**Issue by luispuerto** [sethrfore/homebrew-r-srf#13]
Hey! 

I just updated to Mojave (clean install & new computer) and I'm not able to get X11 capabilities: 

```
> capabilities()
       jpeg         png        tiff       tcltk         X11        aqua    http/ftp 
       TRUE        TRUE        TRUE        TRUE       FALSE        TRUE        TRUE 
    sockets      libxml        fifo      cledit       iconv         NLS     profmem 
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE        TRUE 
      cairo         ICU long.double     libcurl 
       TRUE        TRUE        TRUE        TRUE 
```

I really don't know what I'm missing. 

Any idea? 

I had problems with the `tcltk` support, and then I realize in Mojave a further step is needed. Now I can't get around this. I have `xquarz` installed of course.

**Comment by sethrfore** [comment]
Howdy, if you haven't already, reinstall xquartz which can be necessary after updating your OS. Logout or restart afterwards to update DISPLAY variable. You may then need to rebuild r and cairo... I'm not sure if its necessary to reinstall the formulas but if things don't work as is, do that next. If you reinstalled xquartz and restarted your computer prior to installing the relevant formulas, let me know and we'll go from there.

**Comment by luispuerto** [comment]
Damn it @sethrfore!! you nailed it!! 

What stupid thing... I needed to just restart the mac after reinstalling `xquarz`. 

Thanks a lot for the help!
