### ISSUE TITLE
TclTk issues Catalina

### ISSUE THREAD

**Issue by giriarteS** [sethrfore/homebrew-r-srf#16]
Processor: 2.20GHz Intel Core i7
Memory: 16 GB
System Version: macOS 10.14.6 (18G95)
Xcode: Version: 11.1

Describe the bug:
I tried to install R using sethrfore/r-srf with additional arguments:
`$ brew install sethrfore/r-srf/r --with-openblas --with-java --with-cairo --with-libtiff`
`==> Installing r from sethrfore/r-srf`
`==> Downloading http://cran.r-project.org/src/base/R-3/R-3.6.1.tar.gz`
`######################################################################## 100.0%`
`==> ./configure --prefix=/usr/local/Cellar/r/3.6.1 --enable-memory-profiling --with-x --with-aqua --with-lapack --enable-R-shlib SED`
`==> make`
`Last 15 lines from /Users/gtt/Library/Logs/Homebrew/r/02.make:`
`dyld: lazy symbol binding failed: Symbol not found: _timespec_get`
`Referenced from: /private/tmp/r-20191008-31449-13j1s27/R-3.6.1/lib/libR.dylib`
`Expected in: /usr/lib/libSystem.B.dylib`

`dyld: Symbol not found: _timespec_get`
 `Referenced from: /private/tmp/r-20191008-31449-13j1s27/R-3.6.1/lib/libR.dylib`
 `Expected in: /usr/lib/libSystem.B.dylib`

`/bin/sh: line 1: 45773 Done`                    
`echo "tools:::sysdata2LazyLoadDB(\"./R/sysdata.rda\",\"../../../library/tools/R\")"
     45774 Abort trap: 6           | R_DEFAULT_PACKAGES=NULL LC_ALL=C R_ENABLE_JIT=0 TZ=UTC ../../../bin/R --vanilla --slave`
`make[4]: *** [sysdata] Error 134`
`make[3]: *** [all] Error 2`
`make[2]: *** [R] Error 1`
`make[1]: *** [R] Error 1`
`make: *** [R] Error 1`

`If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/sethrfore/homebrew-r-srf/issues`

**Comment by sethrfore** [comment]
Are both Xcode and Command Line Tools up-to-date? If you updated Xcode without reinstalling Command Line Tools, try that and get back to me.

**Comment by gwinstanley** [comment]
My (re)installation has the same issue, and updating Xcode/tools doesn't fix it, unfortunately.

**Comment by sethrfore** [comment]
Please post the output of `brew config`

**Comment by giriarteS** [comment]
My command line tools SDK headers were 10.4 but my Xcode version was 10.5 (that got updated from the apple store). I uninstalled Xcode and my problem was solved.

**Comment by pascaloettli** [comment]
As I am facing the same issue, here is the output of `brew config` on my computer:
```
HOMEBREW_VERSION: 2.1.14
ORIGIN: https://github.com/Homebrew/brew
HEAD: f1702e51392fd4afcae2b8c521511e43479a1156
Last commit: 18 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9096f82a112202fbffb925b42e7072262047dc90
Core tap last commit: 84 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 11.0 build 1100
Git: 2.21.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 12.0.1, 1.8.0_212, 1.8.0_172
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 11.1
XQuartz: 2.7.11 => /opt/X11
```

**Comment by gwinstanley** [comment]
My system is running macOS 10.14.6 (18G103), and I currently have Xcode 11.0 (11A420a) with updated command-line tools. I also installed the 10.14 headers as specified, to ensure they're found for Tcl/Tk.

`brew config` gives:
```
HOMEBREW_VERSION: 2.1.14-21-g455bb3e
ORIGIN: https://github.com/Homebrew/brew
HEAD: 455bb3e05b6588cd18f4793ec83a25e8e8521fb7
Last commit: 24 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 45e7caab3c5f9d6245263e67883d893bb9d11b48
Core tap last commit: 23 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 11.0 build 1100
Git: 2.23.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 13, 12.0.2, 1.8.0_221
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 11.0
XQuartz: 2.7.11 => /opt/X11
```

**Comment by sethrfore** [comment]
Ok, there are several things going on here... Some are relate to specific user configurations and others relate to changes in Xcode/CLTs. As I'm not an expert in this stuff, I'm not exactly sure how to handle the whole thing. 

With specific regard to the original issue, this seems to relate to mismatch in Xcode/CLT versions. Both @gwinstanley and @pascaloettli have Xcode 11.x installed but have CLT 10.3. It seems Xcode updates may not always trigger an update to CLTs. Regardless, either delete your current CLTs and trigger a new installation via `xcode-select --install` or go to the Apple Developer [website](https://developer.apple.com/download/more/) (create free account if necessary) and download/install Command Line Tools for Xcode 11. This should fix the `dyld: lazy symbol binding failed: Symbol not found: _timespec_get` issue.

However, if/when you update your configurations you will run into issues with TclTk functionality. I've raised a separate issue in order to address this.

**Comment by sethrfore** [comment]
CLTs have more or less been relocated inside the Xcode app. When Xcode says it's up to date, it doesn't seem to be looking at the external CLT installation but rather internally. While I don't know exactly whats going on, the mismatch is evident in your brew config.

**Comment by pascaloettli** [comment]
For an unknown reason, while having Xcode 11.1, `xcode-select --install` installs CLT 10.3. I had to manually install the correct version of CLT `11.0` together with Xcode `11.0`.

**Comment by gwinstanley** [comment]
So, I uninstalled CLT as requested (`sudo rm -rf /Library/Developer/CommandLineTools`), then installed the updated 11.0 version available from the Apple Developer downloads site (_Command_Line_Tools_for_Xcode_11.dmg_). Now my `brew config` shows:
```
CLT: 11.0.0.0.1.1567737322
Xcode: 11.0
CLT headers: 11.0.0.0.1.1567737322
```
which looks a lot more promising. However, nuking the old CLT removed the SDK headers, and they no longer seem to be available in the version from the Apple Dev website, so trying to compile fails to find the Tcl/Tk headers as needed:
```
checking for /System/Library/Frameworks/Tk.framework/tkConfig.sh... /System/Library/Frameworks/Tk.framework/tkConfig.sh
./configure: line 41186: /System/Library/Frameworks/Tcl.framework/tclConfig.sh: No such file or directory
```
I've searched the new CLT folder & Xcode app folder for a header package, but nothing seems to exist, and there's no header file dev download on the website.

**Comment by sethrfore** [comment]
Yeah, I've become aware of this [issue](https://github.com/sethrfore/homebrew-r-srf/issues/16#issuecomment-542233742). I've created [another issue](https://github.com/sethrfore/homebrew-r-srf/issues/17#issue-507298687) to discuss this directly.

**Comment by gwinstanley** [comment]
Ok, I totally removed Xcode/CLT, then reinstalled Xcode 10.3 and CLT 10.3 (via `xcode-select --install`). Successfully rebuilt R this time using the current formula, so looks as though my somewhat non-technical interpretation may have been along the right lines. Only slight anomaly was a spurious failed `rm` near the end, which I can't seem to trace back to anything in particular, as shown by the this Homebrew output:
```
==> ./configure --prefix=/usr/local/Cellar/r/3.6.1 --enable-memory-profiling --with-x --with-aqua --with-lapack --enable
==> make
==> make install
==> make
==> make install
sh: rm: command not found
🍺  /usr/local/Cellar/r/3.6.1: 2,127 files, 57MB, built in 3 minutes 27 seconds
```

`brew config` output (key parts):
```
HOMEBREW_VERSION: 2.1.14-29-g675e38b
CPU: dodeca-core 64-bit kabylake
Clang: 10.0 build 1001
Java: 13, 12.0.2, 1.8.0_221
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 10.3
XQuartz: 2.7.11 => /opt/X11
```

**Comment by sethrfore** [comment]
Right on @gwinstanley, thanks for the testing.

 For those running the current versions of [Xcode and CLTs](https://github.com/sethrfore/homebrew-r-srf/issues/16#issuecomment-542749990), a hack that works is replacing the `tclConfig.sh` and `tkConfig.sh` filepaths in the R formula with their respective CLTs filepaths, e.g.,

 `--with-tcl=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Tcl.framework/tclConfig.sh`

accompanied by manually editing the `TCL_INCLUDE_SPEC` variable found in said `tclConfig.sh` and `tkConfig.sh` files to the corresponding hard filepath. For example: 

`TCL_INCLUDE_SPEC='-I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Tcl.framework/Versions/8.5/Headers'`

It's probably prudent just to comment out the original line in `tclConfig.sh` and `tkConfig.sh` files located in the CLTs SDK and add a new line beneath with the edited hard coded filepath that points to the appropriate header locations as shown above. 

I've tested this and know it works so long as your config is the same as mine with respect to Xcode and CLTs (see link above). I do not know if running Catalina matters or not. I am.

While this is a non-elegant hack, I don't know enough about this stuff to create the correct fix that honors the `-iwithsysroot` option referenced in the stock CLTs `tclConfig.sh` and `tkConfig.sh` files. For more details see this [issue](https://github.com/sethrfore/homebrew-r-srf/issues/17#issue-507298687).

**Comment by pascaloettli** [comment]
Downgrading to Xcode and CLT version `10.3` is the easiest solution in my case.

**Comment by sethrfore** [comment]
Glad to hear everything works. As a side-note, Homebrew only supports the current version of Xcode and users running older versions may eventually run into issues with other packages and/or dependencies they've installed. In other words, reverting to Xcode/CLTs 10.3 won't be a long-term solution, however, it might be the most expedient option for some users now.

**Comment by gwinstanley** [comment]
Agreed, although [this file](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/os/mac/xcode.rb) suggests Homebrew uses Xcode 10.2.1 as the latest version for macOS 10.14. Wikipedia's [Xcode entry](https://en.wikipedia.org/wiki/Xcode) adds info that the tools behind Xcode 10.3 are the same as those for 10.2.1, along with it being the same major version, which both lends credibility to using it. For now, I plan to stick with Xcode 10.3 on my system until I finally upgrade to macOS 10.15, once it's had a point release or two.

**Comment by sethrfore** [comment]
Good feedback. Thanks for your contributions to the conversation.
