### ISSUE TITLE
TclTk issues on Catalina running Xcode 11.x Command Line Tools 11

### ISSUE THREAD

**Issue by sethrfore** [sethrfore/homebrew-r-srf#17]
After updating to Catalina and the current versions of Xcode 11.x and Command Line Tools 11, TclTk does not appear functional. At least on my machine, this is because the file paths to `tclConfig.sh` and `tkConfig.sh` referenced in the R formula not longer exist. This causes the installation to fail. 

While `tclConfig.sh` and `tkConfig.sh` files are both present in Xcode and CLTs, inserting the corresponding paths, e.g.,

`/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Tcl.framework/tclConfig.sh`

into the R formula does not result in tcltk functionality, although the installation doesn't fail. 

Probably the main issue is the header file path location referenced in `tclConfig.sh` and `tkConfig.sh` files (wherever you find them) uses the `-iwithsysroot` option which is not being recognized. For example, this is found in the file referenced above. 

`TCL_INCLUDE_SPEC='-iwithsysroot /System/Library/Frameworks/Tcl.framework/Versions/8.5/Headers'`

Apparently the `sysroot` file path `/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk` is not defined and as such tcltk headers are not found.

A hack might be to set the `TCL_INCLUDE_SPEC` variable in `tclConfig.sh` and `tkConfig.sh` files to the corresponding hard file path. For example: 

`TCL_INCLUDE_SPEC='-I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Tcl.framework/Versions/8.5/Headers'`

Personally, I do not know how to correctly fix this problem at this point.

**Comment by luispuerto** [comment]
Question. If Cairo is installed out of Homebrew, doesn't it work either? I mean… if the original R release has Cairo support, this has to be possible to be done here in some way.

**Comment by luispuerto** [comment]
@sethrfore @btskinner do you have any update in this front? 
Just **a stupid question**… when you updated to catalina, did you reinstalled XQuartz?

>Note: the use of X11 (including tcltk) requires XQuartz to be installed since it is no longer part of OS X. **Always re-install XQuartz when upgrading your macOS to a new major version.**
Source: https://cran.r-project.org 

I'm asking because I haven't updated, yet, but I'm planning to do it soon. I would like to know if I need to do some tinkering to make things work again.

**Comment by sethrfore** [comment]
Yes, you will have to reinstall Xquartz. After installing Catalina, you will likely end up with a new folder called “Relocated Items” or something to that effect. In it, one of the items will be Your xquartz installation.

**Comment by luispuerto** [comment]
I've heart about that folder called `Relocated items`, but also hear that YMWV. Some people reported some things on that folder and others reported that nothing was moved, while they have similar installs. 

My question was more related if… the install of R with Homebrew with formula is still yielding a "half baked" install on Catalina or it's working as it was on Mojave.

**Comment by sethrfore** [comment]
With reference to the issue with Tcl-Tk, things remain as has been discussed in this thread as far as I know. There are work arounds that have been successful for me. Check out the R formula in the dev-tcltk branch and the commented code for a solution that seems to take care of the issue. The solution posited there would likely need to rerun whenever CLTs is updated, though. It’s not perfect but it works. Other than that, I’ve no better solutions that are more eloquent or permanent.

**Comment by luispuerto** [comment]
Hey! 

Sorry if this just a stupid comment or something. I just updated to Catalina and besides that it's been a little bit a pain in the ass get everything up and running on the R side of things —it could have been worse as in previous macOS updates— I came to the impression that 

```sh
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/tkConfig.sh
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tcl.framework/Versions/8.5/tclConfig.sh
```

Already have the correct lines set: 

```sh
TK_INCLUDE_SPEC='-I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers'
```

Did they update something on XCode or what is going on? 

Perhaps you can merge the `dev-tcltk` branch into master?

**Comment by luispuerto** [comment]
PS/ After update, I had `/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/` and `/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/`

I deleted the latter one.

**Comment by sethrfore** [comment]
Sorry for the delay @luispuerto, I missed the question in your previous comment. 

At least on my OS (macOS: 10.15.2-x86_64, Xcode: 11.3, CLT: 11.0.33.16), the `TCL_INCLUDE_SPEC` and `TK_INCLUDE_SPEC` variables specified in their respective `tclConfig.sh` and `tkConfig.sh` files included in the CLT SDK use the `-iwithsysroot` flag and __not__ the formerly used `-I` flag preceding the file path. 

This is why manually changing the include paths in the config files as shown in https://github.com/sethrfore/homebrew-r-srf/issues/17#issue-507298687 works. This is the solution implemented in the dev-tcltk branch (see comments in code for other instructions). 

Given the issue hasn't been revisited for a couple weeks, you may have already reached a solution. Regardless, I just wanted to address the actual question raised for future reference.

**Comment by luispuerto** [comment]
Just wondering if Apple fixed the issue and we didn't realize. I updated to 10.15.2 the other day and then built the new R 3.6.2 ~~without an issue~~.

Now I see that the `tcltk` weren't enabled and I needed to change those lined in those files and rebuild. 

It's really a pity and it would be great to find a solution, since this is the best way to build the best and fastest R available.

**Comment by sethrfore** [comment]
I don't know if Apple would regard this as an issue to be fixed but rather an issue with how Homebrew interacts with Xcode and CLTs in a way affecting certain path variables during installation. But I don't really know...

I would presume the reason for loosing tcltk functionality after updating OS/Xcode/CLTs is because the `tclConfig.sh` and `tkConfig.sh` files were reverted to their original state and the `TCL_INCLUDE_SPEC` and `TK_INCLUDE_SPEC` variables referenced therein now use the `-iwithsysroot` flag rather than the `-I` flag. Whereas we know the former flag won't work, replacing it with the latter will.

**Comment by miguelangelperg** [comment]
Could this alternative option help with the goal?

https://ryanhomer.github.io/posts/build-openmp-macos-catalina-complete

**Comment by luispuerto** [comment]
@miguelangelperg interesting… but you aren't installing R with homebrew, but the R from the cran and them implementing other perks to build packages —if I understood it correctly from skimming the article. 

He isn't using openBLAS as a library, for example, which is part of the improvement. R from cran is using BLAS but not the improved OpenBLAS. As far as I understood. 
I don't see the improvement on that guide. 

Anyhow, perhaps there are some solution to our problem.

**Comment by alazarolop** [comment]
What about the `brew install tcl-tk` line. Could this formula be used to get the functionality perhaps?

**Comment by miguelangelperg** [comment]
@luispuerto True, it is a mixed way to install R. The reasons for installing R from CRAN, according to the author is:

> If you’re already a brew fan and have had to install R, you most like did so with `brew install r`. This is probably the wrong choice for most people as this could prevent R from using pre-built binaries when installing packages

**Comment by luispuerto** [comment]
@alazarolop as far as I know you already need to do `brew install tcl-tk` before you install to get the tcl-tk functionality —at least I did— but then you need to do the hand mode. 

>If you’re already a brew fan and have had to install R, you most like did so with `brew install r`. This is probably the wrong choice for most people as this could prevent R from using pre-built binaries when installing packages 

If you don't build certain packages you are not getting the goodies of BLAS, LLVN and OpenMP as far as I know. 

Do you have a lot of problems building packages? I have some, from time to time, that usually I'm able to solve.

**Comment by alazarolop** [comment]
@luispuerto Ouh, I missed this part during the installation of sethrfore formula. I actually edited the formula locally with genuine hard path to macOS Developers Tools files so to avoid the installation failure. At the end, I installed it, but without `tcl-tk` functionality. 

For the next point release I will try to use the package too. Thanks!

**Comment by luispuerto** [comment]
In other words, you can't have the cake and eat it too. If you are already in the business of install everything with brew, you are already going _rogue_ on the eyes of R Core Team. They don't encourage the use of homebrew because for their eyes could be a source of problems (they are right) so no support for you. 

However, they see it in good light —this was told to me by one of the members of the core team— since as much people know the entrails of R, the better.

**Comment by miguelangelperg** [comment]
I am starting a new environment in a "new" machine with os x Catalina. I was trying to get ahead of the problems that will appear.

I just started and I found Xquartz (saved in Utilities) and Wine that doesn't want to walk in Catalina

**Comment by luispuerto** [comment]
@miguelangelperg I wanted to do a guide… but I haven't had time to be honest. I have also a new computer (bought at the end of june) and it was a little bit a pain in the ass, but I assure you that it's totally doable.

**Comment by sethrfore** [comment]
@miguelangelperg @alazarolop

> Could this alternative option help with the goal?

> 
> https://ryanhomer.github.io/posts/build-openmp-macos-catalina-complete

Thanks for bringing that to my attention. While it is a nice, well written guide if you want to make use of different compiler options, I don't think it resolves any issues with tcltk in regard to this formula. It would be helpful if the author showed the output of `capabilities()` after the installation to verify tcltk is actually functional. I suspect it isn't. This is because the CRAN R.app installation requires an [X11-based tcltk](https://cran.r-project.org/doc/manuals/r-release/R-admin.html#Tcl_002fTk-headers-and-libraries) and the homebrew version is [Aqua-based](https://github.com/Homebrew/homebrew-core/blob/699ef52b5bc06b918fdb92fdbd13b1c2800d9ed3/Formula/tcl-tk.rb#L72). I'm also not sure what installing homebrew tcl-tk after the R.app does considering tcl-tk is a keg-only formula and consequently wouldn't be found by either the R installation or other packages without editing the Makevars, Makeconf or some other configuration files.

@luispuerto 
I'm not sure what `brew install tcl-tk` fixes given it is keg-only and would not be detected when running the standard `brew install sethrfore/r-srf/r --options`. When I edit the relevant lines in the master branch formula to point to the homebrew tcl-tk config files (e.g., /usr/local/Cellar/tcl-tk/8.6.10/lib/tclConfig.sh), the installation errors out. In short, I haven't been able to make R play nice with homebrew tcl-tk for a while now and I'm not aware of any R configuration based on this formula that successfully links to it without losing some other functionalities. However, just because I haven't been successful doesn't mean it can't be done :)

Other than using the homebrew cask R version, the only way I've been able to successfully compile R with tcl-tk has been discussed [here](https://github.com/sethrfore/homebrew-r-srf/issues/16#issuecomment-542903533) and is implemented in the [dev-tcltk](https://github.com/sethrfore/homebrew-r-srf/tree/dev-tcltk) branch of this repository. 

If anyone installs using the dev-tcltk branch, **consult the comments in the formula code** prior to installation. Otherwise your build with fail. 

As always, I'm willing to consider suggestions that increase the functionality of the formula without breaking other stuff.

**Comment by luispuerto** [comment]
perhaps @jfperini has some idea to fix this?

**Comment by yukio-takeuchi** [comment]
I took a bit different approach to define additional environment variables and to over-write variables defined in tclConfig.sh and tkConfig.sh provided by SDK as follows  in formula
``` 
# At least these changes are needed for catalina
tclConfig.sh and tkConfig.sh 
    if MacOS.version == "10.15"
      ENV["TCL_INCLUDE_SPEC"] = "-I#{MacOS.sdk_path}/System/Library/Frameworks/Tcl.framework/Versions/8.5/Headers"
      ENV["TK_INCLUDE_SPEC"] = "-I#{MacOS.sdk_path}/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers"
      ENV["TCLTK_CPPFLAGS"] = "-I#{MacOS.sdk_path}/System/Library/Frameworks/Tcl.framework/Versions/8.5/Headers \
                -I#{MacOS.sdk_path}/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers"
      ENV["TCLTK_LIBS"] = "-F#{MacOS.sdk_path}/System/Library/Frameworks -framework Tk \
               -F#{MacOS.sdk_path}/System/Library/Frameworks -framework Tcl"
end
```

And in args
```
args = [
      "--prefix=#{prefix}",
      "--enable-memory-profiling",
      "--with-x", # SRF - Add X11 support (comment --without-x). Necessary for tcl-tk support.
      "--with-aqua",
      "--with-lapack",
      "--enable-R-shlib",
      "SED=/usr/bin/sed", # don't remember Homebrew's sed shim
      "--with-tcltk", # SRF - Add tcl-tk support.
      # "--with-tcl-config=/System/Library/Frameworks/Tcl.framework/tclConfig.sh", # SRF - Point to system tcl config file (requires Command Line tools to be installed).
      "--with-tcl-config=#{MacOS.sdk_path}/System/Library/Frameworks/Tcl.framework/tclConfig.sh",
     ## "--with-tk-config=/System/Library/Frameworks/Tk.framework/tkConfig.sh" # SRF - Point to system tk config file (requires Command Line tools to be installed).
      "--with-tk-config=#{MacOS.sdk_path}/System/Library/Frameworks/Tk.framework/tkConfig.sh"   
    ]
```
In my Mac (Mac OS 10.15.2), these changes seems working 
```
Rscript -e "capabilities()"
       jpeg         png        tiff       tcltk         X11        aqua
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE
   http/ftp     sockets      libxml        fifo      cledit       iconv
       TRUE        TRUE        TRUE        TRUE       FALSE        TRUE
        NLS     profmem       cairo         ICU long.double     libcurl
       TRUE        TRUE       FALSE        TRUE        TRUE        TRUE
```
I hope, this may help someone.

**Comment by luispuerto** [comment]
@yukio-takeuchi Hey! 

Why don't you do a PR??

**Comment by yukio-takeuchi** [comment]
OK, I just made a [PR](https://github.com/sethrfore/homebrew-r-srf/pull/24#issue-395337106)

**Comment by sethrfore** [comment]
Merged @yukio-takeuchi PR into master.
