### ISSUE TITLE
No Cairo capability 

### ISSUE THREAD

**Issue by luispuerto** [sethrfore/homebrew-r-srf#2]
Hi! 

First of all, thanks a lot for this tap since it's really needed to have a homebrew R formula that enable all the R capabilities. Thanks a lot for this. 

Second. I just build and and I set the flag --with-cairo 

```sh 
brew install sethrfore/r-srf/r --with-openblas --with-java --with-cairo --with-libtiff 
==> Installing r from sethrfore/r-srf
==> Downloading https://cran.r-project.org/src/base/R-3/R-3.5.0.tar.gz
Already downloaded: /Users/lpuerto/Library/Caches/Homebrew/r-3.5.0.tar.gz
==> ./configure --prefix=/usr/local/Cellar/r/3.5.0_1 --enable-memory-profiling --with-x --with-aqua --with-lapack --enab
==> make
==> make install
==> make
==> make install
🍺  /usr/local/Cellar/r/3.5.0_1: 2,116 files, 56.1MB, built in 6 minutes 55 seconds
```

but when I ask for `capabilities()` in R I get: 

```
> capabilities()
       jpeg         png        tiff       tcltk         X11        aqua    http/ftp 
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE        TRUE 
    sockets      libxml        fifo      cledit       iconv         NLS     profmem 
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE        TRUE 
      cairo         ICU long.double     libcurl 
      FALSE        TRUE        TRUE        TRUE 
```

is this correct or I'm doing something wrong? 

Of course I have cairo installed

```
brew info cairo                                                                    
cairo: stable 1.14.12 (bottled), HEAD
Vector graphics library with cross-device output support
https://cairographics.org/
/usr/local/Cellar/cairo/1.14.12 (118 files, 5.8MB) *
  Poured from bottle on 2017-12-17 at 15:50:54
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/cairo.rb
==> Dependencies
Build: pkg-config ✔
Required: freetype ✔, fontconfig ✔, libpng ✔, pixman ✔, glib ✔
==> Options
--HEAD
	Install HEAD version
```

**Comment by sethrfore** [comment]
The issue relates to the [removal](https://github.com/Homebrew/homebrew-core/pull/27484) of the `--with-x11` option from the Homebrew core cairo formula. I have supplied a cairo formula in this repo that builds cairo with X11 support by default. Aside from making X11 support standard, this cairo formula is simply a reversion to the commit preceding removal of the `--with-x11` option. Alternatively, if you do not want to install cairo using formula provided here you can install the previous Homebrew core version supporting X11 via:

`brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/1fea60405bf98c6385dfba18c75a7fb667dc3a40/Formula/cairo.rb --with-x11`

If you want, you can pin the formula preventing future updates using: 

`brew pin cairo`

**Comment by luisspuerto** [comment]
Thanks! I didn't realized that sorry...

**Comment by ankanheesun** [comment]
Hi !!!

Is the a way to enable cario capability? Because, even if I install previous Homebrew core version supporting X11 as you said, that feature is still disabled.

Thanks

**Comment by sethrfore** [comment]
I updated the cairo version in this respository to reflect the current Homebrew version. It seems that even if cairo was installed from this repository as instructed, the next step of building R would trigger a reinstallation of the bottled version of cairo as deployed in the main Homebrew repository because of the version mismatch. Try the installation again and let me know what happens.

**Comment by ankanheesun** [comment]
Yes, each time I install R, it will also install bottled version of Cairo (1.16.0) as followed. Then I reinstall Cairo in your repository, it was successful but without X11 support. And one more thing, when I reinstall your Cairo, its path is the correct one (1.14.12) but results from "brew info cairo" always be "cairo: stable 1.16.0 (bottled), HEAD". Do you know why? 

Finally, everything is fine except I am still not able to enable cairo capability in R. Please update your repository to use the right one. 

Thanks in advance.

**Comment by luispuerto** [comment]
@ankanheesun thanks a lot for this because I haven't realized I had the same problem. I've fixed it after the @sethrfore updated. Great work! 

PS/ I think we can close this.
