### ISSUE TITLE
Why not using 'https://cloud.r-project.org/'?

### ISSUE THREAD

**Issue by niheaven** [sethrfore/homebrew-r-srf#20]
Sometimes "http://cran.r-project.org" is too slow...

**Comment by sethrfore** [comment]
Not a bad idea. The justification for this is that the cloud.r-project.org domain provides automatic redirection to servers worldwide and may improve download speeds for some users. I don't know what the potential downsides of implementing this change might be. If any users encounter problems, let me know and I'll revert changes. As of now, this has been merged into the master branch (see commit bc9f25d8089a056386c2411b1baa6afdb9733a4f).
