### ISSUE TITLE
Update to gss package url

### ISSUE THREAD

**Issue by Shmelder** [sethrfore/homebrew-r-srf#28]
It looks like the url for the gss package

https://cloud.r-project.org/src/contrib/gss_2.2-0.tar.gz

needs to be updated to 

https://cloud.r-project.org/src/contrib/gss_2.2-1.tar.gz

**Comment by Shmelder** [comment]
Thanks for making this fix!

**Comment by mdemircan** [comment]
And now to: https://cloud.r-project.org/src/contrib/gss_2.2-2.tar.gz
