### ISSUE TITLE
configure: error: bzip2 library and headers are required

### ISSUE THREAD

**Issue by yukio-takeuchi** [sethrfore/homebrew-r-srf#31]
Does anyone suffer a similar  build  error due to the following configure error 
```
checking if bzip2 version >= 1.0.6... no
checking whether bzip2 support suffices... configure: error: bzip2 library and headers are required
```
when I tried an instllation after upgrading Xcode to version 12.0(12A7209) with clang 12.0.0
```
❯ clang -v
Apple clang version 12.0.0 (clang-1200.0.32.2)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
?

I have not met the build error related to bzip2 until when I upgraded Xcode to version 12.0.
I could not figure out how this can be resolved.
I would like to have your advise if this error  is happening to my Mac.

FYI I attached the build log.
[build_log.txt](https://github.com/sethrfore/homebrew-r-srf/files/5264663/build_log.txt)

**Comment by yukio-takeuchi** [comment]
I appeared that Xcode 12 together with updated CLT caused the problem as discussed [here](https://trac.macports.org/ticket/60976) .

**Comment by sethrfore** [comment]
Thanks for the report. I created another branch called dev-bzip2 which incorporates the solutions that were pointed to in the link you provided. To use this formula, first clone the repo or update your existing one. Navigate to wherever your repos is located and switch to the dev-bzip2 branch. From there you can install the formula as normal e.g., 
`brew install sethrfore/r-srf/r`
or 
`brew install /path/to/your/repo/folder/r.rb`

**Comment by HannesOberreiter** [comment]
Thanks for the quick solution. As it is a bug and should be fixed in an upcoming release, I think your solution with the different branch is good enough.

**Comment by yukio-takeuchi** [comment]
This solution seems working fine at my Mac with MacOS 10.15.7
Thank you for your quick work.

**Comment by sethrfore** [comment]
No problem. Thanks for the feedback and we'll keep changes relegated to its own branch.
