### ISSUE TITLE
Patching fails for dev-bzip2 branch on R 4.0.3

### ISSUE THREAD

**Issue by ModelledCitizen** [sethrfore/homebrew-r-srf#33]
Howdy, appreciate the work you've put into making this formula and maintaining this tap -- let me know if there's more I can do to debug this.

Patch for dev-bzip2 works great on R 4.0.2, but fails when I try to upgrade OR clean build 4.0.3 in homebrew.

```
Error: Failure while executing; `patch -g 0 -f -p1` exited with 1. Here's the output:
patching file configure
Hunk #1 FAILED at 45400.
Hunk #2 FAILED at 46111.
2 out of 2 hunks FAILED -- saving rejects to file configure.rej
patching file m4/R.m4
Hunk #1 FAILED at 3185.
Hunk #2 FAILED at 4182.
2 out of 2 hunks FAILED -- saving rejects to file m4/R.m4.rej
```

**Comment by sethrfore** [comment]
You likely have updated to Xcode/CLT 12.1 which addressed the bzip2 header problem. If so, install the r formula from the master branch. I've updated instructions in the formula README section reflecting this change. If installing from master doesn't work, let me know and we'll go from there.

**Comment by ModelledCitizen** [comment]
Ah, yep -- works perfectly. Thanks so much!
