### ISSUE TITLE
Can't build R missing unicode/uversion.h

### ISSUE THREAD

**Issue by robsalasco** [sethrfore/homebrew-r-srf#46]
```==> Installing sethrfore/r-srf/r --with-libtiff --with-openblas
==> ./configure --prefix=/usr/local/Cellar/r/4.0.5_2 --enable-memory-profiling --with-x --with-aqua --enable-R-shlib SED=/usr/bin/sed --with-blas=-L/usr/local/opt/
==> make
Last 15 lines from /Users/robsalasco/Library/Logs/Homebrew/r/02.make:
making options.d from options.c
making paste.d from paste.c
making platform.d from platform.c
making plot.d from plot.c
making plot3d.d from plot3d.c
making plotmath.d from plotmath.c
making print.d from print.c
platform.c:3214:12: fatal error: 'unicode/uversion.h' file not found```

**Comment by sethrfore** [comment]
Hmmm, everything built just fine on my machine a second ago. I expect the problem relates to formula builds on your machine. Before I'd consider removing icu4c, we'll have to check some other things over. First, if you are installing from the master branch, icu4c is optional. I don't know why icu4c is causing you problems, but if the problem cannot be solved another way, not using it is one option. However, first i would recommend verifying you are on the master branch of this formula, updating your home-brew, and then do:

`brew rm r`
`brew deps -n --1 sethrfore/r-srf/r | xargs brew reinstall`
`brew install sethrfore/r-srf/r --options-that-you-want`

If you've updated your OS recently you might also have to reinstall xquartz and log out afterwards. After trying this, get back to me and we'll go from there.

**Comment by robsalasco** [comment]
I tried the commands you suggest but I have the same error I verified the Formula and I'm in the master branch 🥺

**Comment by sethrfore** [comment]
Ok try a more comprehensive reinstall of dependencies...

`brew deps -n --include-build --include-optional --include-test --include-requirements sethrfore/r-srf/r | xargs brew reinstall`

Let me know what happens then. It also may be due to issues with your .Rprofile, .Renviron or Makevars files if you've every modified them.

**Comment by sethrfore** [comment]
I also did find a potential error in the formula that added icu4c to CPPFLAGS and LDFLAGS regardless of whether icu4c was selected as an install option. I'll push this fix to master as soon and I get done running some tests on my machine.

**Comment by robsalasco** [comment]
now works as expected :)

**Comment by sethrfore** [comment]
Great to hear :)
