### ISSUE TITLE
Missing libxml capability in R 4.2.0

### ISSUE THREAD

**Issue by Wicky2k8** [sethrfore/homebrew-r-srf#54]
Building sethrfore/r-srf/r with all options on my Macbook Pro 2019, running Monterey (12.4), R is still missing the capability for libxml. I'm not sure if it's just not supported or if I'm doing something wrong, but wanted to flag.

If it's currently not supported, would it be possible to add in the future?

```
Tyrone@Kilgore-Sprout ~ % R

R version 4.2.0 (2022-04-22) -- "Vigorous Calisthenics"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin21.5.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[Previously saved workspace restored]

> capabilities()
       jpeg         png        tiff       tcltk         X11        aqua
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE
   http/ftp     sockets      libxml        fifo      cledit       iconv
       TRUE        TRUE       FALSE        TRUE        TRUE        TRUE
        NLS       Rprof     profmem       cairo         ICU long.double
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE
    libcurl
       TRUE
```

Full homebrew build log attached:
[Build Log.txt](https://github.com/sethrfore/homebrew-r-srf/files/8765134/Build.Log.txt)

**Comment by sethrfore** [comment]
Is this causing a specific problem installing a package? The reason I ask is that I have the same output, but when I run a test install of a package reliant on libxml, for instance, `install.packages("xml2")` everything works fine. 

```
> install.packages('xml2')
Installing package into ‘/Users/SethRFore/R-Library’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/xml2_1.3.3.tar.gz'
Content type 'application/x-gzip' length 283965 bytes (277 KB)
==================================================
downloaded 277 KB

* installing *source* package ‘xml2’ ...
** package ‘xml2’ successfully unpacked and MD5 sums checked
** using staged installation
Found pkg-config cflags and libs!
Using PKG_CFLAGS=-I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/libxml2
Using PKG_LIBS=-L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib -lxml2 -lz -lpthread -licucore -lm
** libs
....
```

I do not know why libxml doesn't appear configured in `capabilities()` output but I wouldn't be concerned about anything so long as whatever xml related packages you need are installing correctly.

If you encounter a problem with this let me know and I'll look into it further. Thanks.

**Comment by Wicky2k8** [comment]
Nope, no issues, installing, same situation as you. But curious why it doesn't show as configured, was thinking it might cause issues at some point

**Comment by sethrfore** [comment]
It's likely due to the fact that libxml is not explicitly specified as a dependency in the `r` formula and therefore isn't found in the config log `R CMD config --all`. So long as your home-brew and Xcode installations are playing nicely, I think packages using libxml should pick up the correct paths when they are compiled. Thanks for the heads up, though.
