### ISSUE TITLE
Installation of rJava fails

### ISSUE THREAD

**Issue by rkrug** [sethrfore/homebrew-r-srf#6]
Hi

I used your tap, but couldn't install rJava - even repeated javareconf did not help. I am back to the official one again.

**Comment by sethrfore** [comment]
It's not exactly clear what your error was. Depending on the options used when R was installed there are certain issues that can occur. For example, if you installed R using `--with-icu4c` you may get an rJava error indicating `ld: library not found for -licuuc`. This reflects the fact that the brewed icu4c formula is keg only. The solution in this case is hinted at in the output of `brew info icu4c` where it indicates different ways to find the necessary files. In this case, I can sucessfully install rJava using:

`install.packages('rJava', configure.args = "LDFLAGS=-L/usr/local/opt/icu4c/lib CPPFLAGS=-I/usr/local/opt/icu4c/include")`

If this does not address your issue, then you might get better results with a better description of the problem.

**Comment by rkrug** [comment]
Thanks - working with that.

May be worth adding this to the info part of the formula?

Thanks a lot.

**Comment by sethrfore** [comment]
icu4c include and library paths will be added when R is configured with optional icu4c support. Additional steps should not be required when installing CRAN packages with related dependencies (e.g., rJava).
