### ISSUE TITLE
cairo-quartz-image-surface.c:345:9: error: 

### ISSUE THREAD

**Issue by derqian** [sethrfore/homebrew-r-srf#60]
==> Applying e22d7212acb454daccc088619ee147af03883974.patch
patching file 'src/cairo-quartz-surface.c'
patching file 'src/cairo-quartz-image-surface.c'
patching file 'src/cairo-quartz-surface.c'
patching file 'src/cairo-quartz-image-surface.c'
patching file 'src/cairo-quartz-surface.c'
patching file 'src/cairo-quartz-surface.c'
==> ./configure --enable-svg=yes --enable-tee=yes --with-x --enable-xlib=yes --enable-xlib-xrender=yes --enable-xlib-xcb=yes --enable-xcb=yes --enable-quartz=yes --enable-quartz-image=yes --enable-quartz-font=yes --enable-ft=yes --enable-fc=yes
==> make install
Last 15 lines from /Users/XXX/Library/Logs/Homebrew/cairo-x11/02.make:
  CC       cairo-xcb-surface-core.lo
  CC       cairo-xcb-surface-render.lo
  CC       cairo-xcb-resources.lo
  CC       cairo-quartz-surface.lo
  CC       cairo-quartz-font.lo
  CC       cairo-quartz-image-surface.lo
cairo-quartz-image-surface.c:345:9: error: incompatible integer to pointer conversion returning 'cairo_status_t' (aka 'enum _cairo_status') from a function with result type 'cairo_surface_t *' (aka 'struct _cairo_surface *') [-Wint-conversion]
        return _cairo_error (CAIRO_STATUS_NO_MEMORY);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[3]: *** [cairo-quartz-image-surface.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [install] Error 2
make[1]: *** [install-recursive] Error 1
make: *** [install] Error 2

**Comment by sethrfore** [comment]
Compiles fine on my machine. Without any other information, try reinstalling dependencies and then reinstall r.
`brew deps -n sethrfore/r-srf/r | xargs brew reinstall`
