### ISSUE TITLE
Installation fails due to tclConfig.sh

### ISSUE THREAD

**Issue by olferievm** [sethrfore/homebrew-r-srf#9]
Try to install R using brew. Installation fails due to the following issues:

brew install sethrfore/r-srf/r  --with-cairo --with-icu4c --with-java --with-libtiff --with-openblas --with-pango --with-texinfo
==> Installing r from sethrfore/r-srf
==> Downloading https://cran.r-project.org/src/base/R-3/R-3.5.2.tar.gz
Already downloaded: /Users/olferievm/Library/Caches/Homebrew/downloads/f9e3ed7ab493a5b01daad6359931114fc7b9eb6df45e77668dc0a06909e6e3c8--R-3.5.2.tar.gz
==> ./configure --prefix=/usr/local/Cellar/r/3.5.2 --enable-memory-profiling --w
Last 15 lines from /Users/olferievm/Library/Logs/Homebrew/r/01.configure:
checking X11/Intrinsic.h presence... yes
checking for X11/Intrinsic.h... yes
checking for XtToolkitInitialize in -lXt... yes
using X11 ... yes
checking for KeySym... yes
checking X11/Xmu/Atoms.h usability... yes
checking X11/Xmu/Atoms.h presence... yes
checking for X11/Xmu/Atoms.h... yes
checking for XmuInternAtom in -lXmu... yes
checking whether pkg-config knows about cairo and pango... yes
checking whether cairo including pango is >= 1.2 and works... yes
checking for CFStringGetSystemEncoding in CoreFoundation framework... -framework CoreFoundation
checking for /System/Library/Frameworks/Tcl.framework/tclConfig.sh... /System/Library/Frameworks/Tcl.framework/tclConfig.sh
checking for /System/Library/Frameworks/Tk.framework/tkConfig.sh... /System/Library/Frameworks/Tk.framework/tkConfig.sh
./configure: line 38486: /System/Library/Frameworks/Tcl.framework/tclConfig.sh: No such file or directory

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/sethrfore/homebrew-r-srf/issues

This is output of info command.
brew info sethrfore/r-srf/r
sethrfore/r-srf/r: stable 3.5.2
Software environment for statistical computing
https://www.r-project.org/
Not installed
From: https://github.com/sethrfore/homebrew-r-srf/blob/master/r.rb
==> Dependencies
Build: pkg-config ✔
Required: gcc ✔, gettext ✔, jpeg ✔, libpng ✔, pcre ✔, readline ✔, xz ✔
Optional: openblas ✔, texinfo ✔, libtiff ✔, cairo ✔, icu4c ✔, pango ✔
==> Requirements
Required: x11 ✔
Optional: java ✔
==> Options
--with-cairo
	Build with cairo support
--with-icu4c
	Build with icu4c support
--with-java
	Build with java support
--with-libtiff
	Build with libtiff support
--with-openblas
	Build with openblas support
--with-pango
	Build with pango support
--with-texinfo
	Build with texinfo support

To note: There is no files on this location:
/System/Library/Frameworks/Tcl.framework/tclConfig.sh
/System/Library/Frameworks/Tk.framework/tkConfig.sh

The location of files is on:
/System/Library/Frameworks/Tk.framework/Versions/8.5/tkConfig.sh
/System/Library/Frameworks/Tcl.framework/Versions/8.5/tclConfig.sh

**Comment by sethrfore** [comment]
Did you follow all the install instructions given in the README section specifically with respect to instructions pertaining to Mojave if that is your OS? In most cases there are tclConfig.sh and tkConfig.sh symlinks given in the directory specified in the formula. Read the instructions, try again and report back if your issue isn’t solved.

**Comment by olferievm** [comment]
Dear Sethfore,

Actually, I missed the first step. Now the problem is solved. Thank you for the immediate reply.

Mike Olferiev

**Comment by sethrfore** [comment]
No problem, happy to help.

**Comment by Cyianor** [comment]
This has become a problem again (at least for me). It seems that

```
$ sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /

installer: Error - the package path specified was invalid: '/Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg'.
```

does not work anymore and I faintly remember reading somewhere that Apple removed the installer in newer versions of Mojave. Am I doing something wrong or is possibly a different solution needed?

**Comment by sethrfore** [comment]
Yes, Apple has indicated the CLT header package will go away at some point, however, I don't think it's gone yet at least with respect to Mojave running the current version of Xcode (10.2.1) and its associated Command Line Tools package. Further, I'm pretty certain the CLT header package is not installed with the OS installer but rather with the CommandLineTools package from the Apple Developer [site](https://developer.apple.com/download/more/) or by running `xcode-select --install` (if Xcode is already installed). Although, it's certainly possible the OS installer zapped stuff in the /Library/Developer/CommandLineTools directory and hence the problem.

While I don't know the exact cause of the issue, I'd download and reinstall the CommandLineTools package from the Apple Developer site (create an account if necessary) and post back with your results. Running `xcode-select --install` may or may not work as well depending on the state of any previous installations.

**Comment by Cyianor** [comment]
Thanks for the detailed explanation! Downloading the CommandLineTools package from the Apple Developer site did the trick. `xcode-select --install` alone wasn't enough.

Thank you very much!

**Comment by sethrfore** [comment]
No problem!
